CREATE DATABASE COMPANY;

CREATE TABLE EMPLOYEE_DETAILS(
EMP_ID INT NOT NULL,
FIRST_NAME VARCHAR(30),
LAST_NAME VARCHAR(30),
SALARY MONEY,
CITY VARCHAR(30),
PRIMARY KEY (EMP_ID)
);

SELECT * FROM EMPLOYEE_DETAILS

DROP TABLE EMPLOYEE_DETAILS;
SELECT * FROM EMPLOYEE_DETAILS;

CREATE TABLE EMPLOYEE_DETAILS1(
EMP_ID INT NOT NULL,
FIRST_NAME VARCHAR(30),
LAST_NAME VARCHAR(30),
SALARY MONEY,
CITY VARCHAR(30),
PRIMARY KEY (EMP_ID)
);
SELECT * FROM EMPLOYEE_DETAILS1;

INSERT INTO EMPLOYEE_DETAILS1
(
EMP_ID,FIRST_NAME,LAST_NAME,SALARY,CITY
)
VALUES(
101,'SUBHASHISH','DE',4000,'KOLKATA'
);

SELECT * FROM EMPLOYEE_DETAILS1;

UPDATE EMPLOYEE_DETAILS1
SET SALARY = 10000
WHERE EMP_ID =101

SELECT * FROM EMPLOYEE_DETAILS1;

CREATE TABLE CUSTOMER(
CUST_ID INT NOT NULL,
CUST_NAME VARCHAR(10),
CUST_ADDRESS VARCHAR(30),
CUST_PHONE VARCHAR(10)


);

SELECT * FROM CUSTOMER;

INSERT INTO CUSTOMER(
CUST_ID,CUST_NAME,CUST_ADDRESS,CUST_PHONE
)
VALUES(
101,'SUBHA','DARAPUR','8101934682'
),(102,'DAVU','MOYNAPUR','231223586'),(105,'KOLKATA','NEWTOWN','8016447610'),(145,'HIRL','SALTLACK','8585757541')
,(45,'HGHT','TOWN','7845122356');